DROP TYPE IF EXISTS category;
CREATE TYPE category AS ENUM (
    'Breakfast',
    'Omelets',
    'Benedicts',
    'Pancakes',
    'A la Carte',
    'Soups and Salads',
    'Cold Sandwiches',
    'Hot Sandwiches',
    'Burger and Hot Dogs',
    'Entrees',
    'Beverages'
);

CREATE TABLE IF NOT EXISTS menu (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL (4, 2) NOT NULL,
    category TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_user (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
    
);


