DROP TYPE IF EXISTS section;
CREATE TYPE section AS ENUM (
    'Breakfast',
    'Omelets',
    'Benedicts',
    'Pancakes',
    'A la Carte',
    'Soups and Salads',
    'Cold Sandwiches',
    'Hot Sandwiches',
    'Burger and Hot Dogs',
    'Entrees',
    'Beverages'
);

CREATE TABLE IF NOT EXISTS menu (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item TEXT NOT NULL,
    description TEXT,
    price Integer NOT NULL,
    category section TEXT NOT NULL
);
